-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 21:01:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE `mydb`;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1`
(
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_info`
(
    `id`         INT         NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(45) NOT NULL,
    `last_name`  VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user`
(
    `id`           INT         NOT NULL AUTO_INCREMENT,
    `email`        VARCHAR(45) NOT NULL,
    `password`     VARCHAR(45) NOT NULL,
    `user_info_id` INT         NOT NULL,
    PRIMARY KEY (`id`, `user_info_id`),
    INDEX `fk_user_user_info_idx` (`user_info_id` ASC) VISIBLE,
    CONSTRAINT `fk_user_user_info`
        FOREIGN KEY (`user_info_id`)
            REFERENCES `mydb`.`user_info` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction_history`
(
    `id`     INT            NOT NULL AUTO_INCREMENT,
    `from`   VARCHAR(16)    NOT NULL,
    `to`     VARCHAR(16)    NOT NULL,
    `amount` DECIMAL(15, 2) NOT NULL,
    `date`   DATETIME       NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bank_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bank_account`
(
    `id`                     INT            NOT NULL AUTO_INCREMENT,
    `balance`                DECIMAL(15, 2) NOT NULL,
    `type`                   VARCHAR(20)    NOT NULL,
    `user_id`                INT            NOT NULL,
    `user_user_info_id`      INT            NOT NULL,
    `transaction_history_id` INT            NOT NULL,
    PRIMARY KEY (`id`, `user_id`, `user_user_info_id`, `transaction_history_id`),
    INDEX `fk_bank_account_user1_idx` (`user_id` ASC, `user_user_info_id` ASC) VISIBLE,
    INDEX `fk_bank_account_transaction_history1_idx` (`transaction_history_id` ASC) VISIBLE,
    CONSTRAINT `fk_bank_account_user1`
        FOREIGN KEY (`user_id`, `user_user_info_id`)
            REFERENCES `mydb`.`user` (`id`, `user_info_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_bank_account_transaction_history1`
        FOREIGN KEY (`transaction_history_id`)
            REFERENCES `mydb`.`transaction_history` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cards`
(
    `id`              INT         NOT NULL AUTO_INCREMENT,
    `card_number`     VARCHAR(16) NOT NULL,
    `expiry_date`     DATE        NOT NULL,
    `type`            VARCHAR(10) NOT NULL,
    `bank_account_id` INT         NOT NULL,
    PRIMARY KEY (`id`, `bank_account_id`),
    INDEX `fk_cards_bank_account1_idx` (`bank_account_id` ASC) VISIBLE,
    CONSTRAINT `fk_cards_bank_account1`
        FOREIGN KEY (`bank_account_id`)
            REFERENCES `mydb`.`bank_account` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
